import { CustomFieldInput } from "../../components/CategoryValueInputs";
import { useEffect, useState } from 'react';
import { api, type Item } from '../../api';
import { extensions, type CompatibilityRelation, type CompatibilityTarget, type ItemExtensions } from '../../extensionApi';

export function ItemStructuredData({ item, onChanged }: { item: Item; onChanged: (item: Item) => Promise<void> }) {
  const [data, setData] = useState<ItemExtensions | null>(null); const [targets, setTargets] = useState<CompatibilityTarget[]>([]);
  const [draft, setDraft] = useState<Record<string, unknown>>({}); const [relations, setRelations] = useState<CompatibilityRelation[]>([]);
  const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => {
    let active = true;
    void Promise.allSettled([extensions.item(item.public_id), extensions.targets()]).then(([details, choices]) => {
      if (!active) return;
      if (details.status === 'fulfilled') { setData(details.value); setRelations(details.value.compatibility); setDraft({}); }
      if (choices.status === 'fulfilled') setTargets(choices.value);
      setError([details, choices].flatMap((result, index) => result.status === 'rejected' ? [index === 0 ? 'Could not load item properties.' : 'Could not load compatibility choices.'] : []).join(' '));
    });
    return () => { active = false; };
  }, [item.public_id, item.version, retry]);
  async function save() { setBusy(true); setError(''); try { const compatibility = relations.map((relation) => Object.fromEntries(['target', 'status', 'notes', 'source_url', 'adapter'].map((key) => [key, relation[key as keyof CompatibilityRelation] || '']))); const next = await api.updateItem(item, { custom_fields: draft, compatibility }); await onChanged(next); setEditing(false); setRetry(retry + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save structured details'); } finally { setBusy(false); } }
  return <section className="detail-section structured-item-data"><div className="section-heading"><h2>Properties and compatibility</h2><button onClick={() => { if (editing) { setDraft({}); setRelations(data?.compatibility || []); } setEditing(!editing); }}>{editing ? 'Cancel edits' : 'Edit properties'}</button></div>{error && <p role="alert">{error} <button onClick={() => setRetry(retry + 1)}>Retry</button></p>}{data && <><div className="custom-item-fields">{data.field_definitions.map((field) => { const value = Object.hasOwn(draft, field.value_field_id) ? draft[field.value_field_id] : Object.hasOwn(data.custom_fields, field.value_field_id) ? data.custom_fields[field.value_field_id] : field.default; return <div className="custom-field-value" key={field.public_id}><label>{field.label}{field.unit ? ` (${field.unit})` : ''}{field.required ? ' *' : ''}{editing && field.active && !field.retained ? <CustomFieldInput field={field} value={value} onChange={(next) => setDraft({ ...draft, [field.value_field_id]: next })} /> : <strong>{value === null || value === undefined ? 'Not set' : String(value)}</strong>}</label><small>{field.retained ? 'Retained from a previous category' : !field.active ? 'Inactive; value retained' : field.inherited ? `Inherited from ${field.source_category_path}` : field.overrides ? 'Branch override' : field.description}</small></div>; })}{!data.field_definitions.length && <p>No category custom fields defined.</p>}</div>{Boolean(data.projects?.length) && <><h3>Used in projects</h3>{data.projects?.map((project) => <p key={project.requirement_public_id}><a href={`?view=projects&project=${encodeURIComponent(project.public_id)}`}>{project.name}</a> · {project.requirement_name} · {project.status}</p>)}</>}<h3>Works with</h3>{relations.map((relation, index) => <div className="item-compatibility-row" key={`${index}-${relation.target}`}>
      {editing ? <><label>Target<select value={relation.target} onChange={(event) => setRelations(relations.map((row, i) => i === index ? { ...row, target: event.target.value } : row))}><option value="">Choose target</option>{targets.map((target) => <option key={target.public_id} value={target.public_id}>{target.name}{!target.active ? ' (inactive)' : ''}</option>)}</select></label><label>Relationship<select value={relation.status} onChange={(event) => setRelations(relations.map((row, i) => i === index ? { ...row, status: event.target.value } : row))}>{['compatible', 'incompatible', 'requires_adapter', 'partial', 'unknown'].map((status) => <option key={status}>{status}</option>)}</select></label>{(['notes', 'source_url', 'adapter'] as const).map((key) => <label key={key}>{key.replaceAll('_', ' ')}<input value={relation[key]} onChange={(event) => setRelations(relations.map((row, i) => i === index ? { ...row, [key]: event.target.value } : row))} /></label>)}<button onClick={() => setRelations(relations.filter((_, i) => i !== index))}>Remove relationship</button></> : <><a href={`?view=compatibility&target=${encodeURIComponent(relation.target)}`}>{relation.target_name || targets.find((target) => target.public_id === relation.target)?.name || relation.target}</a><strong>{relation.status.replaceAll('_', ' ')}</strong>{relation.notes && <p>{relation.notes}</p>}{relation.adapter && <p>Adapter: {relation.adapter}</p>}{relation.source_url && <a href={relation.source_url} target="_blank" rel="noreferrer">Source</a>}</>}
    </div>)}{!relations.length && <p>Compatibility is not specified. Category membership does not imply compatibility.</p>}{editing && <><button onClick={() => setRelations([...relations, { target: '', status: 'unknown', notes: '', source_url: '', adapter: '' }])}>Add compatibility relationship</button><button className="primary" disabled={busy} onClick={() => void save()}>Save properties and compatibility</button></>}</>}
  </section>;
}
