import { useRef, useState } from 'react';
import { request, flattenLocations, type LocationNode } from '../../api';
import { applyOperation, type PlanningProject } from '../../extensionApi';

export function ProjectActions({ project, locations, busy, perform }: { project: PlanningProject; locations: LocationNode[]; busy: boolean; perform: (action: () => Promise<unknown>) => Promise<boolean> }) {
  const [cloneName, setCloneName] = useState(`${project.name} copy`);
  const [outputName, setOutputName] = useState(project.name);
  const [outputQuantity, setOutputQuantity] = useState('1');
  const [place, setPlace] = useState('unassigned');
  const [buildCount, setBuildCount] = useState(project.multiplier);
  const retry = useRef({ payload: '', id: '' });
  const action = (payload: Record<string, unknown>) => {
    const serialized = JSON.stringify(payload);
    if (retry.current.payload !== serialized) retry.current = { payload: serialized, id: crypto.randomUUID() };
    return perform(() => request(`/api/v1/projects/${project.public_id}/actions`, { method: 'POST', body: JSON.stringify({ ...payload, request_id: retry.current.id }) })).then(saved => { if (saved) retry.current = { payload: '', id: '' }; return saved; });
  };
  const formatter = new Intl.NumberFormat(undefined, { style: 'currency', currency: project.currency });
  const money = (minor: number) => formatter.format(minor / 10 ** formatter.resolvedOptions().maximumFractionDigits!);
  return <><div className="project-budget">{[['Estimate', project.budget.estimated_total_minor], ['Spent', project.budget.actual_spent_minor], ['On order', project.budget.ordered_value_minor], ['Still to buy', project.budget.remaining_estimated_minor]].map(([label, value]) => <span key={label}><small>{label}</small><strong>{money(Number(value))}</strong></span>)}</div>{project.budget.unpriced_lines > 0 && <small>{project.budget.unpriced_lines} unpriced lines — estimates are incomplete.</small>}
    <form className="project-multiplier" onSubmit={event => { event.preventDefault(); void perform(() => applyOperation({ op: 'modify', type: 'project', match: { public_id: project.public_id }, data: { multiplier: buildCount } })); }}><label>Build count<input type="number" min="1" max="10000" required value={buildCount} onChange={event => setBuildCount(Number(event.target.value))} /></label>{buildCount !== project.multiplier && <button disabled={busy}>Scale BOM</button>}</form><div className="compact-actions"><strong>{project.status === 'completed' ? 'Completed' : project.ready ? 'Ready to build' : `${project.progress.missing_lines} required lines missing`}</strong>{project.status !== 'completed' && <button className="primary" disabled={busy || !project.ready} onClick={() => void action({ action: 'finish' })}>Finish project</button>}<details><summary>{project.status === 'completed' ? 'Create output item' : 'Finish with output item'}</summary><form className="compact-form" onSubmit={event => { event.preventDefault(); void action({ action: project.status === 'completed' ? 'output' : 'finish', outputs: [{ name: outputName, quantity: outputQuantity, location_public_id: place }] }); }}><label>Finished item name<input required value={outputName} onChange={event => setOutputName(event.target.value)} /></label><label>Quantity<input required type="number" min="0.001" step="0.001" value={outputQuantity} onChange={event => setOutputQuantity(event.target.value)} /></label><label>Store in<select value={place} onChange={event => setPlace(event.target.value)}>{flattenLocations(locations).map(location => <option key={location.public_id} value={location.public_id}>{location.path}</option>)}</select></label><button disabled={busy || (project.status !== 'completed' && !project.ready)}>Create output item{project.status !== 'completed' ? ' and finish' : ''}</button></form></details><details><summary>More actions</summary><form onSubmit={event => { event.preventDefault(); void action({ action: 'clone', name: cloneName }); }}><label>Clone name<input required value={cloneName} onChange={event => setCloneName(event.target.value)} /></label><button disabled={busy}>Clone project</button></form><small>Copies the BOM and references. Stock allocations, orders, receipts and spending start at zero.</small></details></div>
    {project.notes && <details><summary>Notes</summary><p style={{ whiteSpace: 'pre-wrap' }}>{project.notes}</p></details>}
    {project.links.length > 0 && <div className="compact-actions">{project.links.map((link, index) => <a key={index} href={link.url} target="_blank" rel="noreferrer">{link.label}</a>)}</div>}
    <details><summary>Files{project.files.length ? ` · ${project.files.length}` : ''}</summary>{project.files.map(file => <div className="compact-actions" key={file.public_id}><a href={`/api/v1/project-files/${file.public_id}/content`}>{file.name}</a><button disabled={busy} onClick={() => void perform(() => request(`/api/v1/project-files/${file.public_id}`, { method: 'DELETE' }))}>Remove</button></div>)}<label>Attach PDF or image (up to 20 MB)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={busy} onChange={event => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('file', file); void perform(() => request(`/api/v1/projects/${project.public_id}/files`, { method: 'POST', body })); event.target.value = ''; }} /></label></details>
    {project.outputs.length > 0 && <details><summary>Finished items · {project.outputs.length}</summary>{project.outputs.map((output, index) => <p key={index}><a href={`?view=inventory&item=${output.item_public_id}`}>Open output item</a> · {output.quantity_milli / 1000} pcs</p>)}</details>}
    {project.completions.map(completion => <details key={completion.public_id}><summary>Completion snapshot · {new Date(completion.created_at).toLocaleString()}</summary><pre>{JSON.stringify(completion.snapshot, null, 2)}</pre></details>)}
  </>;
}
