import { useCallback, useEffect, useState } from 'react';
import { api, type Category, type Item, type LocationNode } from '../../api';
import { applyOperation, extensions, quantity, type CompatibilityTarget, type PlanningProject, type Requirement } from '../../extensionApi';
import { RequirementEditor } from './RequirementEditor';
import { RequirementStockPicker } from './RequirementStockPicker';
import { TargetChoices } from './TargetChoices';

export function ProjectsView({ categories, locations, onBack, onOpenItem }: { categories: Category[]; locations: LocationNode[]; onBack: () => void; onOpenItem: (item: Item) => void }) {
  const [projects, setProjects] = useState<PlanningProject[]>([]);
  const [targets, setTargets] = useState<CompatibilityTarget[]>([]);
  const [selected, setSelected] = useState(new URLSearchParams(location.search).get('project') || '');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''); const [description, setDescription] = useState('');
  const [projectTargets, setProjectTargets] = useState<string[]>([]);
  const [editing, setEditing] = useState<Requirement | 'new' | null>(null);
  const [linking, setLinking] = useState<Requirement | null>(null);
  const [stocking, setStocking] = useState<Requirement | null>(null);
  const reload = useCallback(async () => { const results = await Promise.allSettled([extensions.projects(), extensions.targets()]); if (results[0].status === 'fulfilled') setProjects(results[0].value); if (results[1].status === 'fulfilled') setTargets(results[1].value); const failed = results.filter((result) => result.status === 'rejected'); if (failed.length) throw new Error('Projects or compatibility targets could not load'); }, []);
  useEffect(() => { void reload().catch((reason: Error) => setError(reason.message)); }, [reload]);
  const project = projects.find((entry) => entry.public_id === selected);
  async function perform(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await reload(); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : 'Change failed'); return false; } finally { setBusy(false); } }
  const patchRequirement = (entry: Requirement, data: Record<string, unknown>) => perform(() => applyOperation({ op: 'modify', type: 'project_requirement', match: { public_id: entry.public_id }, data }));
  return <section className="workspace-page projects-page"><header className="workspace-header"><button onClick={onBack}>Back to More</button><h1>Projects</h1><p>Plan what you need, see what you own, and keep orders separate from physical stock.</p></header>{error && <p role="alert" className="error-banner">{error} <button onClick={() => void perform(reload)}>Retry</button></p>}
    <div className="planning-layout"><aside><h2>Your projects</h2>{projects.map((entry) => <button className={`project-choice ${entry.public_id === selected ? 'active' : ''}`} key={entry.public_id} onClick={() => { setSelected(entry.public_id); const params = new URLSearchParams(location.search); params.set('project', entry.public_id); history.replaceState(history.state, '', `?${params}`); }}><strong>{entry.name}</strong><span>{entry.status} · {entry.progress?.percent || 0}% covered</span></button>)}<details><summary>Create project</summary><form className="form-card compact-form" onSubmit={(event) => { event.preventDefault(); void perform(() => applyOperation({ op: 'add', type: 'project', data: { name, description, compatibility: projectTargets } })).then((saved) => { if (saved) { setName(''); setDescription(''); } }); }}><label>Name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><TargetChoices targets={targets} values={projectTargets} onChange={setProjectTargets} /><button className="primary" disabled={busy}>Create project</button></form></details></aside>
    {project ? <div className="project-detail"><h2>{project.name}</h2>{project.description && <p>{project.description}</p>}<div className="project-progress"><strong>{project.progress.percent}% covered</strong><progress value={project.progress.percent} max={100} aria-label="Project stock coverage" /><span>{project.progress.completed_lines}/{project.progress.total_lines} lines covered · {project.progress.missing_lines} missing</span>{Object.entries(project.progress.quantities_by_unit).map(([unit, totals]) => <small key={unit}>{totals.covered} / {totals.required} {unit}</small>)}</div><details><summary>Project details</summary><ProjectEditor key={`${project.public_id}-${project.status}-${project.name}`} project={project} targets={targets} busy={busy} onSave={(data) => perform(() => applyOperation({ op: 'modify', type: 'project', match: { public_id: project.public_id }, data }))} /></details><button className="primary" onClick={() => setEditing('new')}>Add requirement</button>
      <p className="muted">Missing = required − allocated inventory − acquired outside inventory. Purchased means ordered, not received. Reservations are optional; requirements never consume inventory automatically.</p>
      {project.requirements.map((entry) => <article className={`requirement-card ${entry.satisfied ? 'satisfied' : ''}`} key={entry.public_id}><header><h3>{entry.name}</h3><strong>{entry.status === 'cancelled' ? 'Cancelled' : entry.satisfied ? 'Covered' : `Missing ${entry.missing_quantity} ${entry.unit}`}</strong></header><dl className="requirement-quantities">{[['Required', entry.required_quantity], ['Inventory available', entry.inventory_quantity_available], ['Acquired outside inventory', entry.acquired_quantity], ['Ordered, not received', entry.purchased_quantity]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value} {entry.unit}</dd></div>)}</dl>{entry.notes && <p>{entry.notes}</p>}{entry.warnings.map((warning) => <p className="muted" key={warning}>{warning}</p>)}<div className="requirement-actions"><button disabled={busy} onClick={() => setEditing(entry)}>Edit / adjust quantities</button><button disabled={busy} onClick={() => setLinking(entry)}>{entry.item ? 'Change linked stock' : 'Link inventory'}</button>{entry.item && <><button disabled={busy} onClick={() => void api.item(entry.item!).then(onOpenItem).catch((reason: Error) => setError(reason.message))}>Open item</button><button disabled={busy || Number(entry.missing_quantity) === 0} onClick={() => void patchRequirement(entry, { inventory_quantity: quantity(Number(entry.inventory_quantity) + Math.min(1, Number(entry.missing_quantity))) })}>Use 1 from inventory</button></>}<button disabled={busy || Number(entry.to_buy_quantity) === 0} onClick={() => void patchRequirement(entry, { purchased_quantity: quantity(Number(entry.purchased_quantity) + Number(entry.to_buy_quantity)) })}>Mark missing stock purchased</button><button disabled={busy || Number(entry.missing_quantity) === 0} onClick={() => { const amount = Math.min(1, Number(entry.missing_quantity)); void patchRequirement(entry, { acquired_quantity: quantity(Number(entry.acquired_quantity) + amount), purchased_quantity: quantity(Math.max(0, Number(entry.purchased_quantity) - amount)) }); }}>Mark acquired +1</button><button disabled={busy || Number(entry.acquired_quantity) === 0} onClick={() => void patchRequirement(entry, { acquired_quantity: quantity(Math.max(0, Number(entry.acquired_quantity) - 1)) })}>Undo acquired −1</button><button disabled={busy || Number(entry.acquired_quantity) === 0} onClick={() => setStocking(entry)}>Add acquired stock to inventory</button></div></article>)}
    </div> : <div className="empty-inline"><p>Choose a project or create one. Planned requirements do not need an inventory item yet.</p></div>}</div>
    {project && editing && <RequirementEditor error={error} entry={editing === 'new' ? null : editing} project={project.public_id} categories={categories} targets={targets} busy={busy} onClose={() => setEditing(null)} onSave={async (data) => { const saved = await perform(() => applyOperation({ op: editing === 'new' ? 'add' : 'modify', type: 'project_requirement', ...(editing !== 'new' ? { match: { public_id: editing.public_id } } : {}), data })); if (saved) setEditing(null); }} />}
    {project && (linking || stocking) && <RequirementStockPicker error={error} entry={(linking || stocking)!} project={project.public_id} locations={locations} mode={linking ? 'link' : 'stock'} busy={busy} onClose={() => { setLinking(null); setStocking(null); }} onApply={async (action) => { const saved = await perform(action); if (saved) { setLinking(null); setStocking(null); } }} />}
  </section>;
}

function ProjectEditor({ project, targets, busy, onSave }: { project: PlanningProject; targets: CompatibilityTarget[]; busy: boolean; onSave: (data: Record<string, unknown>) => Promise<boolean> }) {
  const [values, setValues] = useState({ name: project.name, description: project.description, notes: project.notes, status: project.status, compatibility: project.compatibility });
  return <form className="form-card compact-form" onSubmit={(event) => { event.preventDefault(); void onSave(values); }}><label>Name<input required value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} /></label><label>Description<textarea value={values.description} onChange={(event) => setValues({ ...values, description: event.target.value })} /></label><label>Notes<textarea value={values.notes} onChange={(event) => setValues({ ...values, notes: event.target.value })} /></label><label>Status<select value={values.status} onChange={(event) => setValues({ ...values, status: event.target.value })}>{['planned', 'active', 'completed', 'archived'].map((status) => <option key={status}>{status}</option>)}</select></label><TargetChoices targets={targets} values={values.compatibility} onChange={(compatibility) => setValues({ ...values, compatibility })} /><button disabled={busy}>Save project</button></form>;
}
