import { useState } from 'react';
import type { Category } from '../../api';
import type { CompatibilityTarget, Requirement } from '../../extensionApi';
import { TargetChoices } from './TargetChoices';

export function RequirementEditor({ entry, project, categories, targets, busy, error, onClose, onSave }: { entry: Requirement | null; project: string; categories: Category[]; targets: CompatibilityTarget[]; busy: boolean; error?: string; onClose: () => void; onSave: (data: Record<string, unknown>) => Promise<void> }) {
  const [values, setValues] = useState({ project, name: entry?.name || '', category: entry?.category ? String(entry.category) : '', item: entry?.item || '', required_quantity: entry?.required_quantity || '1', inventory_quantity: entry?.inventory_quantity || '0', acquired_quantity: entry?.acquired_quantity || '0', purchased_quantity: entry?.purchased_quantity || '0', unit: entry?.unit || 'pcs', reserve: entry?.reserve || false, notes: entry?.notes || '', status: entry?.status || 'needed', compatibility: entry?.compatibility || [] });
  const quantities = ['required_quantity', 'inventory_quantity', 'acquired_quantity', 'purchased_quantity'] as const;
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={entry ? 'Edit requirement' : 'Add requirement'}><section className="planning-dialog"><header><h2>{entry ? 'Edit requirement' : 'Add requirement'}</h2><button aria-label="Close requirement editor" onClick={onClose}>Close</button></header>{error && <p role="alert">{error}</p>}<form className="form-card compact-form" onSubmit={(event) => { event.preventDefault(); void onSave({ ...values, category: values.category ? Number(values.category) : null, item: values.item || null }); }}><label>Name<input required value={values.name} onChange={(event) => setValues({ ...values, name: event.target.value })} /></label><label>Category<select value={values.category} onChange={(event) => setValues({ ...values, category: event.target.value })}><option value="">Uncategorised</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.path}</option>)}</select></label><details><summary>Advanced inventory reference</summary><label>Linked item public ID<input value={values.item} onChange={(event) => setValues({ ...values, item: event.target.value, inventory_quantity: '0' })} placeholder="Leave blank for a planned item" /></label><p>Or save the requirement and use Link inventory to choose stock by name and place.</p></details>{quantities.map((key) => <label key={key}>{key.replaceAll('_', ' ')}<input inputMode="decimal" value={values[key]} required onChange={(event) => setValues({ ...values, [key]: event.target.value })} /></label>)}<label>Unit<input required value={values.unit} onChange={(event) => setValues({ ...values, unit: event.target.value })} /></label><label><input type="checkbox" checked={values.reserve} onChange={(event) => setValues({ ...values, reserve: event.target.checked })} />Reserve allocated inventory</label><label>Status<select value={values.status} onChange={(event) => setValues({ ...values, status: event.target.value })}>{['needed', 'in_progress', 'satisfied', 'cancelled'].map((status) => <option key={status}>{status}</option>)}</select></label><TargetChoices targets={targets} values={values.compatibility} onChange={(compatibility) => setValues({ ...values, compatibility })} label="Requirement compatibility (empty uses project defaults)" /><label>Notes<textarea value={values.notes} onChange={(event) => setValues({ ...values, notes: event.target.value })} /></label><p>Inventory quantity is an allocation, acquired is outside inventory, and purchased is still on order. These fields replace quantities; they do not increment them.</p><button className="primary" disabled={busy}>Save requirement</button></form></section></div>;
}
