import { useEffect, useState } from 'react';
import { api, type ImportPreviewDetail } from '../../api';
import { extensions, operationBatch, type CategoryField } from '../../extensionApi';
import { parseImportJson } from '../data-tools/strictJson';

const definitionKeys = ['category', 'overrides', 'key', 'label', 'description', 'type', 'required', 'nullable', 'default', 'allowed_values', 'constraints', 'unit', 'sort_order', 'active'];
export function CategoryFieldsPanel({ category, name, onClose }: { category: number; name: string; onClose: () => void }) {
  const [fields, setFields] = useState<CategoryField[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<Record<string, unknown> | null>(null); const [id, setId] = useState<string | null>(null);
  const [advanced, setAdvanced] = useState(''); const [review, setReview] = useState<ReturnType<typeof operationBatch> | null>(null); const [details, setDetails] = useState<ImportPreviewDetail[]>([]);
  useEffect(() => { void extensions.fields(category).then(setFields).catch((reason: Error) => setError(reason.message)); }, [category]);
  function edit(field?: CategoryField) { const values = field ? Object.fromEntries(definitionKeys.map((key) => [key, field[key as keyof CategoryField]])) : { category, key: '', label: '', description: '', type: 'string', required: false, nullable: true, default: null, allowed_values: [], constraints: {}, unit: '', sort_order: 0, active: true, overrides: null }; const inherited = field && field.category !== category; if (inherited) { values.category = category; values.overrides = field.public_id; } setId(field && !inherited ? field.public_id : null); setEditing(values); setAdvanced(JSON.stringify(values, null, 2)); setReview(null); setDetails([]); }
  function change(key: string, value: unknown) { const next = { ...editing, [key]: value }; setEditing(next); setAdvanced(JSON.stringify(next, null, 2)); setReview(null); }
  async function preview() { if (!editing) return; setBusy(true); setError(''); const payload = operationBatch({ op: id ? 'modify' : 'add', type: 'category_field', ...(id ? { match: { public_id: id } } : {}), data: editing }); try { payload.operations[0].data = parseImportJson(advanced); const result = await api.importPreview(payload); setDetails(result.details || []); setReview(result.valid ? payload : null); if (!result.valid) setError(result.errors?.join('\n') || 'Definition is invalid'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Preview failed'); } finally { setBusy(false); } }
  async function apply() { if (!review) return; setBusy(true); setError(''); try { await api.importMerge(review); setFields(await extensions.fields(category)); setReview(null); setEditing(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Save failed'); } finally { setBusy(false); } }
  return <section className="workspace-card category-fields-panel"><header><h2>Custom fields · {name}</h2><button onClick={onClose}>Close fields</button></header><p>Fields inherit down the category tree. Override an inherited field here to give this branch a more specific definition. Values keep their stable identity.</p>{error && <p role="alert" className="error-banner">{error}</p>}<div className="field-definition-list">{fields.map((field) => <article key={field.public_id}><div><strong>{field.label}</strong><small>{field.key} · {field.type}{field.unit ? ` (${field.unit})` : ''} · {field.required ? 'required' : 'optional'}{!field.active ? ' · inactive' : ''}</small><small>{field.inherited ? 'Inherited from ' : 'Defined in '}{field.source_category_path}{field.overrides ? ' · overrides ancestor' : ''}</small><small>{field.affected_items} stored item values</small></div><button onClick={() => edit(field)}>{field.category !== category ? 'Override here' : 'Edit definition'}</button></article>)}</div><button onClick={() => edit()}>Add field</button>
    {editing && <form className="form-card compact-form" onSubmit={(event) => { event.preventDefault(); void preview(); }}><h3>{id ? 'Edit definition' : editing.overrides ? 'Create branch override' : 'New field'}</h3><label>Key<input required pattern="[a-z][a-z0-9_]*" value={String(editing.key || '')} onChange={(event) => change('key', event.target.value)} /></label><label>Display label<input required value={String(editing.label || '')} onChange={(event) => change('label', event.target.value)} /></label><label>Description<textarea value={String(editing.description || '')} onChange={(event) => change('description', event.target.value)} /></label><label>Type<select value={String(editing.type)} onChange={(event) => change('type', event.target.value)}>{['string', 'text', 'integer', 'decimal', 'boolean', 'enum', 'date', 'url'].map((type) => <option key={type}>{type}</option>)}</select></label><label>Unit<input value={String(editing.unit || '')} onChange={(event) => change('unit', event.target.value)} /></label><label>Sort position<input type="number" value={Number(editing.sort_order || 0)} onChange={(event) => change('sort_order', Number(event.target.value))} /></label>{['required', 'nullable', 'active'].map((key) => <label key={key}><input type="checkbox" checked={Boolean(editing[key])} onChange={(event) => change(key, event.target.checked)} />{key}</label>)}{editing.type === 'enum' && <label>Allowed values, one per line<textarea value={(editing.allowed_values as string[] || []).join('\n')} onChange={(event) => change('allowed_values', event.target.value.split('\n').filter(Boolean))} /></label>}<details><summary>Default, validation constraints and complete definition</summary><p>Constraints: min, max, min_length, max_length, decimal_places. Defaults must match the field type. No values are deleted by deactivation.</p><label>Definition JSON<textarea rows={16} value={advanced} onChange={(event) => { setAdvanced(event.target.value); setReview(null); }} /></label><button type="button" onClick={() => { try { const parsed = parseImportJson(advanced); setEditing(parsed); setReview(null); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Invalid definition'); } }}>Use JSON edits</button></details><button type="submit" disabled={busy}>Preview definition change</button><button type="button" onClick={() => { setEditing(null); setReview(null); }}>Cancel</button></form>}
    {details.map((detail) => <div className="import-preview" key={detail.index}><p>{detail.message}</p>{detail.warnings?.map((warning) => <p key={warning}>{warning}</p>)}{detail.after && <details><summary>Resulting definition and affected values</summary><pre>{JSON.stringify(detail.after, null, 2)}</pre></details>}</div>)}{review && <button className="primary" disabled={busy} onClick={() => void apply()}>Apply reviewed field definition</button>}
  </section>;
}
