import { CategoryFieldsPanel } from "./CategoryFieldsPanel";
import { useMemo, useState } from "react";
import { api, type Category, type ConsolidationPreview } from "../../api";
import { usePreferences } from "../shell/usePreferences";
export function CategoryExplorer({ categories, onOpen, onEdit }: { categories: Category[]; onOpen: (id: number) => void; onEdit: (category: Category) => void }) {
  const [fieldCategory, setFieldCategory] = useState<Category | null>(null);
  const { preferences, save, error: preferenceError, reload } = usePreferences();
  const [query, setQuery] = useState('');
  const [mode, setMode] = useState('used');
  const [domain, setDomain] = useState('');
  const [limit, setLimit] = useState(40);
  const [source, setSource] = useState('');
  const [target, setTarget] = useState('');
  const [preview, setPreview] = useState<ConsolidationPreview | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const domains = categories.filter((entry) => entry.parent_id === null);
  const results = useMemo(() => categories.filter((entry) => {
    const matches = entry.path.toLocaleLowerCase().includes(query.toLocaleLowerCase());
    const branch = !domain || entry.path === domain || entry.path.startsWith(`${domain} > `);
    return matches && branch && (query || mode === 'all' || (mode === 'used' ? entry.total_item_count > 0 : preferences.favorite_categories.includes(entry.id)));
  }).sort((a, b) => b.total_item_count - a.total_item_count || a.path.localeCompare(b.path)), [categories, domain, mode, preferences.favorite_categories, query]);
  async function review() { setBusy(true); setError(''); try { setPreview(await api.consolidationPreview(source, target)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not preview consolidation'); } finally { setBusy(false); } }
  async function apply() { if (!preview) return; setBusy(true); try { await api.consolidateCategories(source, target, preview.token); window.location.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not consolidate'); setPreview(null); } finally { setBusy(false); } }
  return <section className="category-explorer"><h1>Categories</h1><p className="muted">Start with the categories you use, or search the full library.</p><label className="search"><input type="search" aria-label="Search all categories" placeholder="Search the full category library" value={query} onChange={(event) => { setQuery(event.target.value); setLimit(40); }} /></label><div className="filter-row">{['used', 'favorites', 'all'].map((value) => <button key={value} className={mode === value ? 'active' : ''} onClick={() => { setMode(value); setLimit(40); }}>{value === 'used' ? 'Used categories' : value === 'favorites' ? 'Favorites' : 'Full library'}</button>)}</div><label>Domain<select value={domain} onChange={(event) => { setDomain(event.target.value); setLimit(40); }}><option value="">All domains</option>{domains.map((entry) => <option key={entry.id} value={entry.path}>{entry.name}</option>)}</select></label><p className="muted">{results.length} categories{query ? ' across the full library' : ''}</p>{preferenceError && <p role="alert">{preferenceError} <button onClick={() => void reload()}>Retry</button></p>}<div className="category-results">{results.slice(0, limit).map((entry) => <article key={entry.id}><button onClick={() => onOpen(entry.id)}><strong>{entry.name}</strong><small>{entry.path} · {entry.total_item_count} items</small></button><button onClick={() => onEdit(entry)}>Edit</button><button onClick={() => setFieldCategory(entry)}>Custom fields</button><button aria-pressed={preferences.favorite_categories.includes(entry.id)} aria-label={`Favorite ${entry.path}`} onClick={() => void save({ favorite_categories: preferences.favorite_categories.includes(entry.id) ? preferences.favorite_categories.filter((id) => id !== entry.id) : [...preferences.favorite_categories, entry.id] })}>{preferences.favorite_categories.includes(entry.id) ? '★' : '☆'}</button></article>)}</div>{results.length > limit && <button onClick={() => setLimit(limit + 40)}>Show more categories</button>}
    {fieldCategory && <CategoryFieldsPanel key={fieldCategory.id} category={fieldCategory.id} name={fieldCategory.path} onClose={() => setFieldCategory(null)} />}
    <details className="consolidation-panel"><summary>Consolidate item assignments</summary><p>Move items from a category and its children into one category. Existing categories and place rules are retained. The destination determines which optional item fields are shown.</p><div className="form-row"><label>From<select value={source} onChange={(event) => { setSource(event.target.value); setPreview(null); }}><option value="">Choose category</option>{categories.map((entry) => <option key={entry.id} value={entry.id}>{entry.path}</option>)}</select></label><label>Into<select value={target} onChange={(event) => { setTarget(event.target.value); setPreview(null); }}><option value="">Choose destination</option>{categories.filter((entry) => String(entry.id) !== source).map((entry) => <option key={entry.id} value={entry.id}>{entry.path}</option>)}</select></label></div><button disabled={busy || !source || !target} onClick={() => void review()}>Preview impact</button>{error && <p role="alert">{error}</p>}{preview && <div className="import-preview"><h3>{preview.item_count} items will change category</h3><p>{preview.source} → {preview.target}</p><p>{preview.categories_retained} source categories retained. {preview.source_rules.length} matching place rules retained. Existing item locations stay as they are.</p><p>Destination default: {preview.target_defaults?.name || 'No default place'}.</p><details><summary>Review affected items and rules</summary><ul>{preview.items.map((item) => <li key={item.public_id}>{item.name}</li>)}{preview.source_rules.map((rule) => <li key={rule.public_id}>Rule retained: {rule.match_value}</li>)}</ul></details><button className="primary" disabled={busy || preview.item_count === 0} onClick={() => void apply()}>Apply reviewed reassignment</button></div>}</details>
  </section>;
}
