import { useState } from "react";
import { api, type Category, type ConsolidationPreview } from "../../api";
export function CategoryConsolidation({ categories, categoryId }: { categories: Category[]; categoryId: number }) {
  const [source, setSource] = useState(String(categoryId));
  const [target, setTarget] = useState('');
  const [preview, setPreview] = useState<ConsolidationPreview | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  async function review() { setBusy(true); setError(''); try { setPreview(await api.consolidationPreview(source, target)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not preview consolidation'); } finally { setBusy(false); } }
  async function apply() { if (!preview) return; setBusy(true); try { await api.consolidateCategories(source, target, preview.token); window.location.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not consolidate'); setPreview(null); } finally { setBusy(false); } }
  return (<details className="consolidation-panel"><summary>Consolidate item assignments</summary><p>Move items from a category and its children into one category. Existing categories and place rules are retained. The destination determines which optional item fields are shown.</p><div className="form-row"><label>From<select value={source} onChange={(event) => { setSource(event.target.value); setPreview(null); }}><option value="">Choose category</option>{categories.map((entry) => <option key={entry.id} value={entry.id}>{entry.path}</option>)}</select></label><label>Into<select value={target} onChange={(event) => { setTarget(event.target.value); setPreview(null); }}><option value="">Choose destination</option>{categories.filter((entry) => String(entry.id) !== source).map((entry) => <option key={entry.id} value={entry.id}>{entry.path}</option>)}</select></label></div><button disabled={busy || !source || !target} onClick={() => void review()}>Preview impact</button>{error && <p role="alert">{error}</p>}{preview && <div className="import-preview"><h3>{preview.item_count} items will change category</h3><p>{preview.source} → {preview.target}</p><p>{preview.categories_retained} source categories retained. {preview.source_rules.length} matching place rules retained. Existing item locations stay as they are.</p><p>Destination default: {preview.target_defaults?.name || 'No default place'}.</p><details><summary>Review affected items and rules</summary><ul>{preview.items.map((item) => <li key={item.public_id}>{item.name}</li>)}{preview.source_rules.map((rule) => <li key={rule.public_id}>Rule retained: {rule.match_value}</li>)}</ul></details><button className="primary" disabled={busy || preview.item_count === 0} onClick={() => void apply()}>Apply reviewed reassignment</button></div>}</details>);
}
