import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api, type Category, type Item, type Loan, type Project } from "../../api";
import { Icon } from "../../components/Icon";
import { capabilitiesForCategory } from "../capture/itemCaptureUtils";

function isLost(item: Item) { return item.tags.some((tag) => tag.toLowerCase() === "lost"); }

export function InventoryManagementView({ items, categories, busy, onBack, onChanged, onOpenItem, onMarkFound, onForeverLost, setNotice }: {
  items: Item[]; categories: Category[]; busy: boolean; onBack: () => void; onChanged: () => Promise<void>;
  onOpenItem: (item: Item) => void; onMarkFound: (item: Item) => Promise<void>; onForeverLost: (item: Item) => Promise<void>; setNotice: (message: string) => void;
}) {
  const [projects, setProjects] = useState<Project[]>([]); const [loans, setLoans] = useState<Loan[]>([]); const [archived, setArchived] = useState<Item[]>([]); const [activity, setActivity] = useState("");
  const [projectName, setProjectName] = useState(""); const [projectDescription, setProjectDescription] = useState(""); const [reserveProject, setReserveProject] = useState(""); const [reserveItem, setReserveItem] = useState(""); const [reserveQuantity, setReserveQuantity] = useState("1");
  const [loanItem, setLoanItem] = useState(""); const [loanPerson, setLoanPerson] = useState(""); const [loanDirection, setLoanDirection] = useState<"lent" | "borrowed">("lent"); const [loanDue, setLoanDue] = useState("");
  const lost = useMemo(() => items.filter(isLost), [items]);
  const reservable = useMemo(() => items.filter((item) => capabilitiesForCategory(categories, item.category_id).reservation), [categories, items]);
  const load = useCallback(async () => { try { const [nextProjects, nextLoans, nextArchived] = await Promise.all([api.projects(), api.loans(), api.archivedItems()]); setProjects(nextProjects); setLoans(nextLoans); setArchived(nextArchived); setReserveProject((value) => value || nextProjects.find((entry) => entry.status === "active")?.public_id || ""); setReserveItem((value) => value || reservable[0]?.public_id || ""); setLoanItem((value) => value || items[0]?.public_id || ""); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load inventory management"); } }, [items, reservable, setNotice]);
  useEffect(() => { void load(); }, [load]);
  async function perform(action: () => Promise<unknown>, success: string) { setActivity("Saving changes…"); try { await action(); await load(); setNotice(success); } catch (error) { setNotice(error instanceof Error ? error.message : "The action could not be completed"); } finally { setActivity(""); } }
  async function createProject(event: FormEvent) { event.preventDefault(); await perform(() => api.createProject(projectName, projectDescription), "Project created"); setProjectName(""); setProjectDescription(""); }
  async function reserve(event: FormEvent) { event.preventDefault(); const project = projects.find((entry) => entry.public_id === reserveProject); const item = reservable.find((entry) => entry.public_id === reserveItem); if (project && item) await perform(() => api.reserveItem(project, item, reserveQuantity), `${item.name} reserved`); }
  async function createLoan(event: FormEvent) { event.preventDefault(); await perform(() => api.createLoan({ item_public_id: loanItem, direction: loanDirection, person: loanPerson, quantity: "1", due_date: loanDue || null, notes: "" }), "Loan recorded"); setLoanPerson(""); setLoanDue(""); }
  async function restore(item: Item) { await perform(async () => { await api.restoreItem(item.public_id); await onChanged(); }, `${item.name} restored`); }
  async function hardDelete(item: Item) { if (!window.confirm(`Delete ${item.name} forever? This removes its photos and history and cannot be undone.`)) return; await perform(async () => { await api.hardDeleteItem(item); await onChanged(); }, `${item.name} permanently deleted`); }
  const openLoans = loans.filter((loan) => !loan.returned_at); const activeProjects = projects.filter((project) => project.status === "active");
  return <section className="workspace-page inventory-management-page"><header className="workspace-header"><button className="text-button workspace-back" onClick={onBack}><Icon name="chevron" size={16} />Extra</button><p className="eyebrow">INVENTORY MANAGEMENT</p><h1>Keep inventory life organized</h1><p>Recover archived items, resolve missing things, coordinate projects, and track what has left your hands.</p></header>{activity && <div className="inline-activity" role="status"><span className="activity-spinner" />{activity}</div>}<nav className="workspace-jump" aria-label="Inventory management sections"><a href="#lost-items">Lost <b>{lost.length}</b></a><a href="#archived-items">Archived <b>{archived.length}</b></a><a href="#projects">Projects <b>{activeProjects.length}</b></a><a href="#loans">Borrowed & lent <b>{openLoans.length}</b></a></nav>
    <section id="lost-items" className="workspace-card"><header><span><Icon name="search" /></span><div><p className="eyebrow">LOST ITEMS</p><h2>{lost.length ? `${lost.length} waiting to be found` : "Everything is accounted for"}</h2><p>Open an item for context, mark it found, or retire it when it is gone for good.</p></div></header><div className="lost-list">{lost.length === 0 && <div className="empty-inline"><span>No lost items</span></div>}{lost.map((item) => <article className="lost-row" key={item.public_id}><button type="button" className="lost-main" onClick={() => onOpenItem(item)}><span><Icon name="search" size={17} /></span><div><strong>{item.name}</strong><small>{item.location_path}</small></div></button><div className="lost-actions"><button className="secondary" onClick={() => void onMarkFound(item)}><Icon name="check" size={14} />Found</button><button onClick={() => void onForeverLost(item)}><Icon name="close" size={14} />Forever lost</button></div></article>)}</div></section>
    <section id="archived-items" className="workspace-card"><header><span><Icon name="box" /></span><div><p className="eyebrow">ARCHIVE</p><h2>{archived.length ? `${archived.length} archived items` : "Archive is empty"}</h2><p>Restore items to Inventory or permanently erase records you no longer need.</p></div></header><div className="archived-list">{archived.map((item) => <article className="archived-row" key={item.public_id}>{item.primary_photo_url ? <img src={item.primary_photo_url} alt="" /> : <span className="archived-placeholder"><Icon name="box" /></span>}<div className="archived-main"><strong>{item.name}</strong><small>{item.location_path}{item.category_path ? ` · ${item.category_path}` : ""}</small><time>{item.archived_at ? `Archived ${new Date(`${item.archived_at}Z`).toLocaleString()}` : "Archived recently"}</time></div><div className="archived-actions"><button className="secondary" disabled={busy} onClick={() => void restore(item)}>Restore</button><button className="danger-button" disabled={busy} onClick={() => void hardDelete(item)}>Delete forever</button></div></article>)}</div></section>
    <section id="projects" className="workspace-card"><header><span><Icon name="tag" /></span><div><p className="eyebrow">PROJECTS & RESERVATIONS</p><h2>Set stock aside with purpose</h2><p>Reserve inventory for active work so quantities stay visible and intentional.</p></div></header><div className="management-columns"><div>{projects.map((project) => <article className="manage-card" key={project.public_id}><header><div><strong>{project.name}</strong><small>{project.status}</small></div><div className="project-actions">{project.status === "active" && <button onClick={() => void perform(() => api.setProjectStatus(project, "completed"), "Project completed")}>Complete</button>}<button onClick={() => void perform(() => api.deleteProject(project), "Project deleted")}>Delete</button></div></header>{project.description && <p>{project.description}</p>}{project.reservations.map((entry) => <div className="reservation" key={entry.item_public_id}><span>{entry.item_name}</span><small>{entry.quantity} {entry.unit}</small><button aria-label={`Remove ${entry.item_name} reservation`} onClick={() => void perform(() => api.removeReservation(project, entry.item_public_id), "Reservation removed")}><Icon name="close" /></button></div>)}</article>)}</div><div><form className="form-card compact-form" onSubmit={createProject}><strong>New project</strong><label>Name<input required value={projectName} onChange={(event) => setProjectName(event.target.value)} /></label><label>Description<input value={projectDescription} onChange={(event) => setProjectDescription(event.target.value)} /></label><button className="secondary">Create project</button></form>{activeProjects.length > 0 && reservable.length > 0 && <form className="form-card compact-form" onSubmit={reserve}><strong>Reserve inventory</strong><label>Project<select value={reserveProject} onChange={(event) => setReserveProject(event.target.value)}>{activeProjects.map((project) => <option key={project.public_id} value={project.public_id}>{project.name}</option>)}</select></label><label>Item<select value={reserveItem} onChange={(event) => setReserveItem(event.target.value)}>{reservable.map((item) => <option key={item.public_id} value={item.public_id}>{item.name} · {item.quantity} {item.unit}</option>)}</select></label><label>Quantity<input inputMode="decimal" value={reserveQuantity} onChange={(event) => setReserveQuantity(event.target.value)} /></label><button className="primary">Reserve item</button></form>}</div></div></section>
    <section id="loans" className="workspace-card"><header><span><Icon name="user" /></span><div><p className="eyebrow">BORROWED & LENT</p><h2>{openLoans.length ? `${openLoans.length} open records` : "Nothing is currently out"}</h2><p>See who has what, what you borrowed, and when each item should return.</p></div></header><div className="management-columns"><div>{openLoans.map((loan) => <article className="loan-card" key={loan.public_id}><div><strong>{loan.item_name}</strong><p>{loan.direction === "lent" ? `Lent to ${loan.person}` : `Borrowed from ${loan.person}`}</p><small>{loan.due_date ? `Due ${loan.due_date}` : "No due date"}</small></div><button onClick={() => void perform(() => api.returnLoan(loan), "Marked as returned")}>Returned</button></article>)}</div><form className="form-card compact-form" onSubmit={createLoan}><strong>Record a loan</strong><label>Item<select value={loanItem} onChange={(event) => setLoanItem(event.target.value)}>{items.map((item) => <option key={item.public_id} value={item.public_id}>{item.name}</option>)}</select></label><div className="form-row"><label>Direction<select value={loanDirection} onChange={(event) => setLoanDirection(event.target.value as "lent" | "borrowed")}><option value="lent">I lent it</option><option value="borrowed">I borrowed it</option></select></label><label>Person<input required value={loanPerson} onChange={(event) => setLoanPerson(event.target.value)} /></label></div><label>Due date<input type="date" value={loanDue} onChange={(event) => setLoanDue(event.target.value)} /></label><button className="primary" disabled={!loanItem}>Record loan</button></form></div></section>
  </section>;
}
